CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423084954_InitialCreate') THEN
    CREATE TABLE "Leads" (
        "Id" uuid NOT NULL,
        "Email" text NOT NULL,
        "FirstName" text,
        "LastName" text,
        "Score" integer NOT NULL,
        "Stage" integer NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        "LastActivityUtc" timestamp with time zone NOT NULL,
        "LastScoredAtUtc" timestamp with time zone,
        CONSTRAINT "PK_Leads" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423084954_InitialCreate') THEN
    CREATE TABLE "Events" (
        "Id" uuid NOT NULL,
        "LeadId" uuid NOT NULL,
        "Type" integer NOT NULL,
        "Source" integer NOT NULL,
        "SuspectedBot" boolean NOT NULL,
        "MetadataJson" text,
        "TimestampUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Events" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Events_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423084954_InitialCreate') THEN
    CREATE INDEX "IX_Events_LeadId_Type_TimestampUtc" ON "Events" ("LeadId", "Type", "TimestampUtc");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423084954_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Leads_Email" ON "Leads" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260423084954_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260423084954_InitialCreate', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424120704_AddCompanyProductConfigs') THEN
    CREATE TABLE "CompanyProductConfigs" (
        "Id" uuid NOT NULL,
        "CompanyName" text NOT NULL,
        "ProductName" text NOT NULL,
        "ProductId" integer NOT NULL,
        "ProductEventConfigJson" text NOT NULL,
        "CreatedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CompanyProductConfigs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424120704_AddCompanyProductConfigs') THEN
    CREATE UNIQUE INDEX "IX_CompanyProductConfigs_CompanyName_ProductName_ProductId" ON "CompanyProductConfigs" ("CompanyName", "ProductName", "ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260424120704_AddCompanyProductConfigs') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260424120704_AddCompanyProductConfigs', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427095838_AddEmailTemplates') THEN
    CREATE TABLE "EmailTemplates" (
        "TemplateId" integer GENERATED BY DEFAULT AS IDENTITY,
        "Name" text NOT NULL,
        "Stage" integer NOT NULL,
        "Subject" text NOT NULL,
        "EmailBodyHtml" text NOT NULL,
        "CtaButtonText" text,
        "CtaLink" text,
        "IsTrackingEnabled" boolean NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone,
        CONSTRAINT "PK_EmailTemplates" PRIMARY KEY ("TemplateId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427095838_AddEmailTemplates') THEN
    CREATE UNIQUE INDEX "IX_EmailTemplates_Stage" ON "EmailTemplates" ("Stage") WHERE "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260427095838_AddEmailTemplates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260427095838_AddEmailTemplates', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428105756_AddProductScopedEmailTemplates') THEN
    DROP INDEX "IX_EmailTemplates_Stage";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428105756_AddProductScopedEmailTemplates') THEN
    ALTER TABLE "EmailTemplates" ADD "ProductId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428105756_AddProductScopedEmailTemplates') THEN
    CREATE UNIQUE INDEX "IX_EmailTemplates_Stage_ProductId" ON "EmailTemplates" ("Stage", "ProductId") WHERE "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428105756_AddProductScopedEmailTemplates') THEN
    INSERT INTO public."EmailTemplates" ("Name", "ProductId", "Stage", "Subject", "EmailBodyHtml", "CtaButtonText", "CtaLink", "IsTrackingEnabled", "IsActive", "CreatedAt", "UpdatedAt")
    SELECT
        v."Name",
        v."ProductId",
        v."Stage",
        v."Subject",
        v."EmailBodyHtml",
        v."CtaButtonText",
        v."CtaLink",
        v."IsTrackingEnabled",
        v."IsActive",
        NOW(),
        NULL
    FROM (
        VALUES
        (
            'Welcome - Cold Stage (Product 1)',
            1,
            0,
            'Your hiring pipeline is leaking top talent',
            $cold$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr>
          <td align="center">
            <table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
              <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
              <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Your hiring pipeline is leaking top talent</td></tr>
              <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">While you are manually screening resumes, your best candidates are already interviewing elsewhere. Faster hiring systems consistently win top talent.</td></tr>
              <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">HiperBrains automates screening, scheduling, interviews, and evaluation so your team can focus on decisions instead of admin work.</td></tr>
              <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>$cold$,
            'VIEW ENTERPRISE PRICING',
            'https://www.hiperbrains.com/enterprise?event={{event}}_cold_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - Warm Stage (Product 1)',
            1,
            1,
            'Explore real hiring use cases for your industry',
            $warm$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr>
          <td align="center">
            <table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
              <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
              <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Explore real hiring use cases for your industry</td></tr>
              <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">You have already shown interest in pricing, events, blogs, and platform pages. Now see how HiperBrains solves hiring for technology and SaaS teams in real workflows.</td></tr>
              <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">Compare outcomes, understand role-based workflows, and discover how teams move from sourcing to offer decisions with less effort.</td></tr>
              <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>$warm$,
            'EXPLORE USE CASES',
            'https://www.hiperbrains.com/use-cases/technology-saas?event={{event}}_warm_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - MQL Stage (Product 1)',
            1,
            2,
            'See the full HiperBrains hiring platform in action',
            $mql$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr>
          <td align="center">
            <table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
              <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
              <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">See the full HiperBrains hiring platform in action</td></tr>
              <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">At this stage, the fastest way to decide is a personalized walkthrough. We will map your hiring flow, role types, and current bottlenecks.</td></tr>
              <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">Get answers on security, process design, integrations, and deployment expectations for your team size.</td></tr>
              <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>$mql$,
            'BOOK A PERSONALIZED DEMO',
            'https://www.hiperbrains.com/enterprise?event={{event}}_mql_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - Hot Stage (Product 1)',
            1,
            3,
            'Final invite: launch your hiring platform today',
            $hot$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr>
          <td align="center">
            <table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
              <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
              <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Final invite: launch your hiring platform today</td></tr>
              <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">You have already visited pricing, events, blog, and use-case pages. Join now and turn hiring speed into a measurable business advantage.</td></tr>
              <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">Set up your workspace, define interview flows, and start hiring with AI-supported decisions from day one.</td></tr>
              <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
            </table>
          </td>
        </tr>
      </table>
    </body>
    </html>$hot$,
            'SIGN UP & JOIN HIPERBRAINS',
            'https://www.hiperbrains.com/?event={{event}}_hot_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        )
    ) AS v("Name", "ProductId", "Stage", "Subject", "EmailBodyHtml", "CtaButtonText", "CtaLink", "IsTrackingEnabled", "IsActive")
    WHERE NOT EXISTS (
        SELECT 1
        FROM public."EmailTemplates" t
        WHERE t."ProductId" = v."ProductId"
          AND t."Stage" = v."Stage"
          AND t."IsActive" = true
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428105756_AddProductScopedEmailTemplates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428105756_AddProductScopedEmailTemplates', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428112617_AddFollowUpEmailTemplates') THEN
    DROP INDEX "IX_EmailTemplates_Stage_ProductId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428112617_AddFollowUpEmailTemplates') THEN
    ALTER TABLE "EmailTemplates" ADD "IsFollowUp" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428112617_AddFollowUpEmailTemplates') THEN
    CREATE UNIQUE INDEX "IX_EmailTemplates_Stage_ProductId_IsFollowUp" ON "EmailTemplates" ("Stage", "ProductId", "IsFollowUp") WHERE "IsActive" = true;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428112617_AddFollowUpEmailTemplates') THEN
    INSERT INTO public."EmailTemplates" ("Name", "ProductId", "IsFollowUp", "Stage", "Subject", "EmailBodyHtml", "CtaButtonText", "CtaLink", "IsTrackingEnabled", "IsActive", "CreatedAt", "UpdatedAt")
    SELECT
        v."Name",
        v."ProductId",
        v."IsFollowUp",
        v."Stage",
        v."Subject",
        v."EmailBodyHtml",
        v."CtaButtonText",
        v."CtaLink",
        v."IsTrackingEnabled",
        v."IsActive",
        NOW(),
        NULL
    FROM (
        VALUES
        (
            'Welcome - Cold Follow-up (Product 1)',
            1,
            true,
            0,
            'Still reviewing resumes manually?',
            $coldf$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
          <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
          <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Still reviewing resumes manually?</td></tr>
          <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">Hiring speed decides outcomes. Teams that respond first secure stronger candidates and reduce offer drop-offs.</td></tr>
          <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">From AI job descriptions to final evaluation, every step is connected on one platform for consistency and speed.</td></tr>
          <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
        </table></td></tr>
      </table>
    </body>
    </html>$coldf$,
            'EXPLORE HOW HIPERBRAINS WORKS',
            'https://www.hiperbrains.com/about?event={{event}}_cold_followup_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - Warm Follow-up (Product 1)',
            1,
            true,
            1,
            'You explored. Now launch your hiring workflow',
            $warmf$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
          <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
          <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">You explored. Now launch your hiring workflow.</td></tr>
          <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">Since you have checked use cases and pricing, this is the best time to start. Set up your company and begin hiring smarter in minutes.</td></tr>
          <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">Recruiters, interviewers, and hiring managers can collaborate in one place with structured, consistent scoring.</td></tr>
          <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
        </table></td></tr>
      </table>
    </body>
    </html>$warmf$,
            'SIGN UP NOW',
            'https://www.hiperbrains.com/?event={{event}}_warm_followup_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - MQL Follow-up (Product 1)',
            1,
            true,
            2,
            'Ready to move from evaluation to rollout?',
            $mqlf$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
          <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
          <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Ready to move from evaluation to rollout?</td></tr>
          <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">You have engaged with core pages and product intent signals. This is the right moment to activate your account and move to implementation.</td></tr>
          <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">Need stakeholder buy-in first? We can align on pricing, ROI goals, and onboarding milestones with your team.</td></tr>
          <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
        </table></td></tr>
      </table>
    </body>
    </html>$mqlf$,
            'START SIGNUP',
            'https://www.hiperbrains.com/?event={{event}}_mql_followup_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        ),
        (
            'Welcome - Hot Follow-up (Product 1)',
            1,
            true,
            3,
            'Final invite: launch your hiring platform today',
            $hotf$<!DOCTYPE html>
    <html>
    <body style="margin:0;padding:0;background-color:#021f33;font-family:Arial,sans-serif;">
      <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="background-color:#021f33;padding:24px 0;">
        <tr><td align="center"><table role="presentation" width="620" cellspacing="0" cellpadding="0" style="max-width:620px;background-color:#032844;color:#ffffff;padding:28px;border-radius:8px;">
          <tr><td style="font-size:34px;font-weight:700;color:#6af47c;padding-bottom:10px;">HiperBrains</td></tr>
          <tr><td style="font-size:38px;line-height:1.2;font-weight:700;padding-bottom:12px;">Final invite: launch your hiring platform today</td></tr>
          <tr><td style="font-size:18px;line-height:1.5;color:#d8f3ff;padding-bottom:22px;">This is your final reminder to activate HiperBrains. You have done the research - now convert that intent into execution.</td></tr>
          <tr><td style="font-size:17px;line-height:1.5;padding-bottom:20px;">If you would like a quick alignment call before starting, our team can help with setup, scope, and rollout planning.</td></tr>
          <tr><td style="font-size:12px;line-height:1.5;color:#9ec9da;">HiperBrains, 4100 Spring Valley Road, Suite 710, Farmers Branch, Dallas, TX 75244, United States</td></tr>
        </table></td></tr>
      </table>
    </body>
    </html>$hotf$,
            'CREATE ACCOUNT',
            'https://www.hiperbrains.com/?event={{event}}_hot_followup_primary&email={{email}}&leadId={{leadId}}',
            true,
            true
        )
    ) AS v("Name", "ProductId", "IsFollowUp", "Stage", "Subject", "EmailBodyHtml", "CtaButtonText", "CtaLink", "IsTrackingEnabled", "IsActive")
    WHERE NOT EXISTS (
        SELECT 1
        FROM public."EmailTemplates" t
        WHERE t."ProductId" = v."ProductId"
          AND t."Stage" = v."Stage"
          AND t."IsFollowUp" = v."IsFollowUp"
          AND t."IsActive" = true
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428112617_AddFollowUpEmailTemplates') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428112617_AddFollowUpEmailTemplates', '9.0.3');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE TABLE "BatchConfigs" (
        "ConfigId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "BatchType" integer NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_BatchConfigs" PRIMARY KEY ("ConfigId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE TABLE "Batches" (
        "BatchId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProductId" integer NOT NULL,
        "BatchType" integer NOT NULL,
        "StartTime" timestamp with time zone NOT NULL,
        "EndTime" timestamp with time zone,
        "Status" integer NOT NULL,
        "TotalLeads" integer NOT NULL,
        "SuccessCount" integer NOT NULL,
        "FailedCount" integer NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Batches" PRIMARY KEY ("BatchId")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE TABLE "BatchLeads" (
        "BatchLeadId" bigint GENERATED BY DEFAULT AS IDENTITY,
        "BatchId" bigint NOT NULL,
        "LeadId" uuid NOT NULL,
        "Status" integer NOT NULL,
        "ErrorMessage" text,
        "RetryCount" integer NOT NULL,
        "ProcessedAt" timestamp with time zone,
        CONSTRAINT "PK_BatchLeads" PRIMARY KEY ("BatchLeadId"),
        CONSTRAINT "FK_BatchLeads_Batches_BatchId" FOREIGN KEY ("BatchId") REFERENCES "Batches" ("BatchId") ON DELETE CASCADE,
        CONSTRAINT "FK_BatchLeads_Leads_LeadId" FOREIGN KEY ("LeadId") REFERENCES "Leads" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE INDEX "IX_BatchConfigs_ProductId_IsActive" ON "BatchConfigs" ("ProductId", "IsActive");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE INDEX "IX_Batches_ProductId" ON "Batches" ("ProductId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE INDEX "IX_Batches_ProductId_BatchType_Status_EndTime" ON "Batches" ("ProductId", "BatchType", "Status", "EndTime");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE INDEX "IX_BatchLeads_BatchId" ON "BatchLeads" ("BatchId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    CREATE INDEX "IX_BatchLeads_LeadId" ON "BatchLeads" ("LeadId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260428122643_AddBatchProcessing') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260428122643_AddBatchProcessing', '9.0.3');
    END IF;
END $EF$;
COMMIT;

